In [1]:
import cv2

In [2]:
!pip install opencv-python

  Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 6.7 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.6 MB 7.3 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.6 MB 9.3 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 9.4 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.6 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 10.2 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 9.5 MB/s eta 0:00:00


In [1]:
import cv2

# Print OpenCV version
print(cv2.__version__)


4.10.0


In [2]:
img=cv2.imread("D:/node js back/krti pic.jpeg")
cv2.imshow("ashu",img)
img1=cv2.imread("D:/node js back/sai pallvi pics.webp")
cv2.imshow("ashu1",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()
# cv2.destroyWindow("ashu")





error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:973: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [3]:
import numpy as np
import os 

In [21]:
img3=cv2.imread("D:/node js back/dripti pics.webp")
re_img=cv2.resize(img3,(800,800))
cv2.imshow("ashu3",re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [22]:
print(img)


[[[183 197 216]
  [182 196 215]
  [182 196 215]
  ...
  [174 197 219]
  [173 197 219]
  [173 197 219]]

 [[183 197 216]
  [182 196 215]
  [182 196 215]
  ...
  [167 190 212]
  [167 191 213]
  [168 192 214]]

 [[182 196 215]
  [182 196 215]
  [181 195 214]
  ...
  [157 181 203]
  [159 183 205]
  [161 185 207]]

 ...

 [[ 63  81 118]
  [ 61  79 116]
  [ 58  76 113]
  ...
  [ 26  28  36]
  [ 27  29  37]
  [ 27  29  37]]

 [[ 62  80 117]
  [ 60  78 115]
  [ 57  75 112]
  ...
  [ 29  31  39]
  [ 30  32  40]
  [ 31  33  41]]

 [[ 61  79 116]
  [ 59  77 114]
  [ 56  74 111]
  ...
  [ 31  33  41]
  [ 31  33  41]
  [ 33  35  43]]]


In [5]:
img1=cv2.imread("D:/pics/sai pallvi pics.webp")
re_img=cv2.resize(img1,(300,300))
h=np.hstack((re_img,re_img,re_img,re_img))
v=np.vstack((h,h))
cv2.imshow("ashu1",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
listname=os.listdir("D:/pics")
listname

['demo.mp4',
 'demo1.mp4',
 'demo2.mp4',
 'disha pics.webp',
 'dripti pics.jpg',
 'krti pic.jpeg',
 'merge_img.png',
 'paper.jpg',
 'ppdt.mp4',
 'sai pallvi pics.webp',
 'shurti pics.webp']

In [10]:
for name in listname:
    path="D:/pics"
    img_name=path+"/"+name
    img=cv2.imread(img_name)
    
    cv2.imshow("ashu4",img)
    cv2.waitKey(1000)
cv2.destroyAllWindows()

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:973: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [11]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp",0)

cv2.imshow("ashu1",img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp",-1)

cv2.imshow("ashu1",img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
txt=cv2.putText(
img=img4,
text="Sai pallvi- prettiest smile of the world",
org=(100,100),
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale=1,
color=(0,0,255),
thickness=2,
lineType=cv2.LINE_8)
cv2.imshow("ashu1",img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
new_img=cv2.line(img=img4,pt1=(500,300),pt2=(700,300),color=(0,255,0),thickness=4,lineType=4)
cv2.imshow("ashu1",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
new_img=cv2.rectangle(img=img4,pt1=(390,300),pt2=(710,710),color=(0,255,0),thickness=4,lineType=4)
cv2.imshow("ashu1",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
new_img=cv2.circle(img=img4,center=(500,500),radius=250,color=(0,255,0),thickness=4,lineType=16)
cv2.imshow("ashu1",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
new_img=cv2.ellipse(img=img4,center=(550,450),axes=(200,300),angle=15,startAngle=0,endAngle=360,color=(0,255,0),thickness=4,lineType=16)
cv2.imshow("ashu1",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
new_img=cv2.polylines(img=img4,pts=[np.array([[500,500],[400,300],[400,700],[700,400],[700,700]])],isClosed=True,color=(0,255,0),thickness=4,lineType=16)
cv2.imshow("ashu1",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
img5=cv2.imread("D:/pics/shurti pics.webp")
img1=cv2.resize(img4,(500,500))
img2=cv2.resize(img5,(500,500))
new_img=cv2.addWeighted(img1,1,img2,1,1)
cv2.imshow("ashu1",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
img5=cv2.imread("D:/pics/shurti pics.webp")
img1=cv2.resize(img4,(500,500))
img2=cv2.resize(img5,(500,500))
new_img=cv2.subtract(img1,img2)
cv2.imshow("ashu1",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
img5=cv2.imread("D:/pics/shurti pics.webp")
img1=cv2.resize(img4,(500,500))
img2=cv2.resize(img5,(500,500))
# new_img=cv2.bitwise_xor(img1,img2)
new_img=cv2.bitwise_not(img1)
cv2.imshow("ashu1",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [81]:
#edge detect
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
img1=cv2.resize(img4,(500,500))
new_img=cv2.Canny(img1,500,500,apertureSize=5,L2gradient=False)
cv2.imshow("ashu1",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [86]:
#resize
img4=cv2.imread("D:/pics/dripti pics.jpg")
img1=cv2.resize(img4,(600,700))
w,h=img1.shape[0],img1.shape[1]
m=cv2.getRotationMatrix2D((w/2,h/2),45,1)
new_img=cv2.warpAffine(img1,m,(h))
cv2.imshow("ashu1",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [96]:
#blurring
img4=cv2.imread("D:/pics/dripti pics.jpg")
img1=cv2.resize(img4,(300,300))
g=cv2.GaussianBlur(img1,(7,7),0)
m=cv2.medianBlur(img1,5)
b=cv2.bilateralFilter(img1,9,75,75)
h=np.hstack((img1,g,m,b))
cv2.imshow("ashu1",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [105]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
img5=cv2.imread("D:/pics/dripti pics.jpg")
img1=cv2.resize(img4,(400,400))
img2=cv2.resize(img5,(400,400))
h=np.hstack((img1,img2))
v=np.vstack((h,h))
cv2.imwrite("D:/pics/merge_img.png",v)
cv2.imshow("ashu1",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [108]:
#make border
img5=cv2.imread("D:/pics/dripti pics.jpg")
img1=cv2.resize(img5,(400,400))
img1=cv2.copyMakeBorder(img1,20,20,20,20,cv2.BORDER_CONSTANT,None,value=2)
cv2.imshow("ashu1",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
cap=cv2.VideoCapture("D:/pics/ppdt.mp4")
while cap.isOpened():
    r,frame=cap.read()
    frame=cv2.resize(frame,(600,400))
   
    if r==True:
        cv2.imshow("ashu1",frame)
        if cv2.waitKey(4) & 0xff == ord("p"):
            break
cap.release()
cv2.destroyAllWindows()

In [11]:
img5=cv2.imread("D:/pics/dripti pics.jpg")

new=cv2.pyrDown(img5)
new1=cv2.pyrDown(new)
new2=cv2.pyrDown(new1)
big_img=cv2.pyrUp(new2)
big_img1=cv2.pyrUp(big_img)
big_img2=cv2.pyrUp(big_img1)
# cv2.imshow("ashu1",new)
# cv2.imshow("ashu2",new1)
cv2.imshow("ashu",big_img)
cv2.imshow("ashu2",big_img1)
cv2.imshow("ashu3",big_img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
img5=cv2.imread("D:/pics/dripti pics.jpg")
img1=cv2.resize(img5,(400,400))
m=np.float32([[1,0,100],[0,1,50]])
new=cv2.warpAffine(img1,m,(400,400))
cv2.imshow("ashu2",img1)
cv2.imshow("ashu3",new)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
cap=cv2.VideoCapture("D:/pics/ppdt.mp4")
sub_m=cv2.createBackgroundSubtractorMOG2()
while True:
    r,frame=cap.read()
    if r==True:
        frame=cv2.resize(frame,(600,400))
        sub_v=sub_m.apply(frame)
        cv2.imshow("ashu3",frame)
        cv2.imshow("ashu",sub_v)
        if cv2.waitKey(25) & 0xff == ord("p"):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()


In [15]:
cap=cv2.VideoCapture("D:/pics/ppdt.mp4")
c=0
while True:
    r,frame=cap.read()
    if r==True:
        frame=cv2.resize(frame,(600,400))
        filename="D:/vpic"+"org_img"+str(c)+".png"
        cv2.imwrite(filename,frame)
        c+=1
        cv2.imshow("ashu3",frame)
        if cv2.waitKey(25) & 0xff == ord("p"):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()
        

In [18]:
img5=cv2.imread("D:/pics/dripti pics.jpg")
img1=cv2.resize(img5,(400,400))
# new=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
# new=cv2.cvtColor(img1,cv2.COLOR_BGR2HSV)
new=cv2.cvtColor(img1,cv2.COLOR_BGR2HLS)
cv2.imshow("ashu3",new)
cv2.imshow("ashu",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
img5=cv2.imread("D:/pics/dripti pics.jpg")
img1=cv2.resize(img5,(400,400))
crop=img1[200:,:]
cv2.imshow("ashu",crop)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
new=np.ones((500,500,3),np.uint8)*255
cv2.imshow("ashu",new)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
new=np.zeros((500,500,3),np.uint8)*255
cv2.imshow("ashu",new)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
def fun(x):
    pass

In [5]:
new=np.zeros((500,500,3),np.uint8)*255
cv2.namedWindow("colour")
cv2.createTrackbar("R","colour",0,255,fun)
cv2.createTrackbar("G","colour",0,255,fun)
cv2.createTrackbar("B","colour",0,255,fun)
while True:
    cv2.imshow("colour",new)
    if cv2.waitKey(25) & 0xff == ord("p"):
        break
    r=cv2.getTrackbarPos("R","colour")
    g=cv2.getTrackbarPos("G","colour")
    b=cv2.getTrackbarPos("B","colour")
    new[:]=[b,g,r]
cv2.destroyAllWindows()

In [9]:
new=np.zeros((500,500,3),np.uint8)
cv2.namedWindow("bar")
cv2.createTrackbar("on","bar",0,100,fun)
while True:
    cv2.imshow("bar",new)
    if cv2.waitKey(1) & 0xff == ord("p"):
        break
    var=cv2.getTrackbarPos("on","bar")
    new[:]=[0,0,var]
cv2.destroyAllWindows()

NameError: name 'fun' is not defined

In [8]:
img5=cv2.imread("D:/pics/dripti pics.jpg")
img5=cv2.resize(img5,(800,800))
crop=img5[105:700,200:650]
img5[105:700,100:550]=crop
cv2.imshow("ashu",img5)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
img4=cv2.imread("D:/pics/sai pallvi pics.webp")
img5=cv2.resize(img4,(500,500))
# img1=cv2.flip(img5,1)  #y-axix about
# img2=cv2.flip(img5,0)  #x-axix about
# img3=cv2.flip(img5,-1)  #x,y-axix about

cv2.imshow("ashu",img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
#gray video
cap=cv2.VideoCapture(0)
f=cv2.VideoWriter_fourcc(*"XVID")
out=cv2.VideoWriter("D:/pics/demo2.mp4",f,25.0,(640,480),0)
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        frame=cv2.flip(frame,1)
        out.write(frame)
        cv2.imshow("ashu",frame)
        if cv2.waitKey(1) & 0xff == ord("p"):
            break
    else:
        break
cap.release()
out.release()
cv2.destroyAllWindows()

In [ ]:
#normalvideo
cap=cv2.VideoCapture(0)
f=cv2.VideoWriter_fourcc(*"XVID")
out=cv2.VideoWriter("D:/pics/demo2.mp4",f,25.0,(640,480))
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        # frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        frame=cv2.flip(frame,1)
        out.write(frame)
        cv2.imshow("ashu",frame)
        if cv2.waitKey(1) & 0xff == ord("p"):
            break
    else:
        break
cap.release()
out.release()
cv2.destroyAllWindows()

In [ ]:
cap=cv2.VideoCapture(0)
def fun(x):
    pass
cv2.namedWindow("color")
cv2.createTrackbar("lR","colour",0,255,fun)
cv2.createTrackbar("lG","colour",0,255,fun)
cv2.createTrackbar("lB","colour",0,255,fun)

cv2.createTrackbar("uR","colour",255,255,fun)
cv2.createTrackbar("uG","colour",255,255,fun)
cv2.createTrackbar("uB","colour",255,255,fun)


In [44]:
img5=cv2.imread("D:/pics/paper.jpg")
cv2.circle(img5,(66,421),4,(0,0,255),-1)
cv2.circle(img5,(432,441),4,(0,0,255),-1)
cv2.circle(img5,(66,669),4,(0,0,255),-1)
cv2.circle(img5,(510,680),4,(0,0,255),-1)
cv2.imshow("ashu",img5)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [47]:
img5=cv2.imread("D:/pics/paper.jpg")
print(img5.shape)

(1280, 576, 3)


In [7]:
img5=cv2.imread("D:/pics/paper.jpg")
w,h=(576,1280)
scr1=np.float32([[66,421],[432,441],[66,669],[510,680]])
dst1=np.float32([[0,0],[w,0],[0,h],[w,h]])
m=cv2.getPerspectiveTransform(scr1,dst1)
new_img=cv2.warpPerspective(img5,m,(w,h))
cv2.imshow("ashu",new_img)
cv2.imshow("ashu1",img5)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
import mediapipe as mp

In [4]:
mp_face_det=mp.solutions.face_detection
mp_draw=mp.solutions.drawing_utils

In [6]:
face_dect=mp_face_det.FaceDetection(min_detection_confidence=1,model_selection=0)
cap=cv2.VideoCapture(0)
while cap.isOpened():
    r,frame=cap.read()
    frame=cv2.flip(frame,1)
    frame=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    result=face_dect.process(frame)

    frame=cv2.cvtColor(frame,cv2.COLOR_RGB2BGR)
    if r==True:
        for cr in result.detections:
            mp_draw.draw_detection(frame,cr)
        cv2.imshow("ashu",frame)
        if cv2.waitKey(1) & 0xff == ord("p"):
            break
    else:
        break
cap.release()

cv2.destroyAllWindows()
          
      